# Generated by Django 5.2.4 on 2025-08-02 13:01

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(default=None, max_length=20, validators=[members.models.validate_international_phone_number])),
                ('joined_date', models.DateField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
    ]
