# Generated by Django 5.2.4 on 2025-07-06 21:45

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_member_user_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[members.models.validate_international_phone_number]),
        ),
    ]
