# Generated by Django 5.2.4 on 2025-07-13 18:22

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_member_email_alter_member_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default=None, max_length=20, validators=[members.models.validate_international_phone_number]),
        ),
    ]
