services:
  db:
    image: postgres:16-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: djangoproject_db
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: djangopassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U djangouser -d djangoproject_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: ./run_django.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy